### ISSUE TITLE
feature request: Hide "Shorts remixing this video" in description

### ISSUE THREAD

**Issue by ItzELECTR0** [Pedro-Gregorio/TubeMod#113]
This blasted thing:
![image](https://github.com/user-attachments/assets/f6f7ccae-c8f1-4e2d-bc55-d4d0a1d6c442)

**Comment by Pedro-Gregorio** [comment]
Hey, Electro! Can take care of this with no problem. Can you just send me the video to spare me some searching? 😄

**Comment by ItzELECTR0** [comment]
Sure thing, it's [this one](https://www.youtube.com/watch?v=rxJtOm68TMk)

**Comment by Pedro-Gregorio** [comment]
Amazing on how we can both open the same video and you see things that I can't 🤣

**Comment by Pedro-Gregorio** [comment]
Done, coming on 1.10.0!
