### ISSUE TITLE
Feature request: hide "AI context/summary" button under videos

### ISSUE THREAD

**Issue by SoundBoomer** [Pedro-Gregorio/TubeMod#116]
Under the description of some videos there is a section where an AI summarizes the video you're currently watching, and I would like to be able to get rid of that.
![изображение](https://github.com/user-attachments/assets/39b5e408-19d7-49f2-a19c-a80445ae24c2)

**Comment by Pedro-Gregorio** [comment]
Hello! Already implemented, coming on 1.10.0. Closing, as duplicate.
