### ISSUE TITLE
New Feature: Hide Video Views

### ISSUE THREAD

**Issue by Pedro-Gregorio** [Pedro-Gregorio/TubeMod#12]
The goal of this feature is to hide video views:
![image](https://github.com/user-attachments/assets/7378e57b-5f57-41ab-bd8b-68c7c2c3ce03)

Could also be applied to every YouTube page, to prevent bias towards choosing what content to watch.

**Comment by Perseus333** [comment]
I wonder how you prefer this to be implemented, if several buttons to tweak views in each menu (suggestions and videos) or one in general(?) to hide them everywhere. I guess the latter would make more sense, but tell me what you had in mind.

**Comment by Pedro-Gregorio** [comment]
Video Views is already implemented in 1.5.0
