### ISSUE TITLE
Feature Request: To change visibility of the timestamps of the video player

### ISSUE THREAD

**Issue by dotexe3301** [Pedro-Gregorio/TubeMod#121]
@Pedro-Gregorio Sometimes when there is a white portion in the YouTube video that hides the time and chapter name as it is in white, there should be a checkbox to change that color to black and make them a little bold.

Youtube video player:
![image](https://github.com/user-attachments/assets/2919fbf0-1002-4eed-9d7b-6e14053bc786)

**Comment by ItzELECTR0** [comment]
Wouldn't a better solution be to either add a black outline or a black background to that particular portion?

**Comment by dotexe3301** [comment]
> Wouldn't a better solution be to either add a black outline or a black background to that particular portion?

According to what I understand, adding a black outline to the box doesn't help as the text would still be in white, and adding a black background makes the text visible but it won't look good on the UI.

**Comment by ItzELECTR0** [comment]
I was referring to a black outline for the text itself to make it stand out from the white background of the video. A black outline for the box would do absolutely nothing.

**Comment by Pedro-Gregorio** [comment]
Hello!
@dotexe3301 can you please share a video in which that problem occurs?

**Comment by dotexe3301** [comment]
> Hello! @dotexe3301 can you please share a video in which that problem occurs?

No, there is no problem in the tubemod. I was suggesting a feature to make the video player time text black for better visibility when the video has white portion in itself.

**Comment by ItzELECTR0** [comment]
> No, there is no problem in the tubemod.

I am pretty sure he was referring to a link to a video where your problem happens, as in where you can't see the text well.
