### ISSUE TITLE
issue: Hide 'Create' button no longer works

### ISSUE THREAD

**Issue by ItzELECTR0** [Pedro-Gregorio/TubeMod#123]
Youtube changed the create button and it no longer can be hidden

![image](https://github.com/user-attachments/assets/e6cf429b-57d1-4326-8e44-e6daac1f6a7e)
![image](https://github.com/user-attachments/assets/bd539c8e-f89f-4f04-b4c8-cb88a0874231)

**Comment by Pedro-Gregorio** [comment]
Fixing this today and sending the code to a newer release, with a couple of changes!

**Comment by ItzELECTR0** [comment]
Foreshadowing for the much anticipated yt studio button? Peak!

**Comment by Pedro-Gregorio** [comment]
Fixed, and fixed the search bar as well, which had the same issue.
Releasing on 1.11.0.
