### ISSUE TITLE
Enhancement: Hide Likes Counter

### ISSUE THREAD

**Issue by Pedro-Gregorio** [Pedro-Gregorio/TubeMod#14]
Instead of hiding the like/dislike button, simply hiding the likes counter would prevent bias - and probably would result in a better UI overall, because both buttons would be without text.

**Comment by Perseus333** [comment]
I made this: #45 that for now does the trick to solve it, but as stated in the description it isn't very pretty as there is a margin in one of the parents that makes it off-center. Maybe in future versions when you plan to implement tweaking the CSS in a more advanced way we could change this but for now that's all I think can be done. 

Also, I selected the path using the `copy XPath` tool from the chrome inspect tab, is this good practice? It creates a really long path but I think at least it's accurate? Idk, let me know if this is the best way to do it or I should find a shorter path manually.

**Comment by Pedro-Gregorio** [comment]
Created a discussion regarding this topic: https://github.com/Pedro-Gregorio/TubeMod/discussions/47

**Comment by Pedro-Gregorio** [comment]
I'm closing this for now. YouTube brings the elements back when it's counter changes - same is happening with views on the description. This will be considered in a later stage, when we "block" elements from loading in the first place.
