### ISSUE TITLE
issue: Firefox Specific - Sidebar options bug

### ISSUE THREAD

**Issue by ItzELECTR0** [Pedro-Gregorio/TubeMod#25]
There is a Firefox specific issue with disabling items in the sidebar. When trying to use an option to disable an element, the one above it gets disable instead.

Example:
Hide Playlists Button -> History Button is hidden
Hide Your Videos Button -> Playlists Button is hidden

The new "Hide YouTube Music" feature doesn't work in Firefox either.
Verified by getting a youtube premium free trial
Tested in Firefox Developer Edition and Opera GX (Worked fine in Opera)

**Comment by Pedro-Gregorio** [comment]
Hey, @ItzELECTR0 ! Thank you for reaching out! Can you confirm that both browsers are using TubeMod in version 1.4.0?

**Comment by ItzELECTR0** [comment]
Yes, both are using 1,4,0

**Comment by Pedro-Gregorio** [comment]
According to @ItzELECTR0 , "unhook affected how TubeMod worked, since Unhooked already removed some elements, when I tried to remove others with TubeMod, they were misplaced. It was an easy fix by just disabling some of my options in Unhook."
