### ISSUE TITLE
Bug: doesn't work on Arc Browser

### ISSUE THREAD

**Issue by Yezo** [Pedro-Gregorio/TubeMod#27]
Attemping to toggle any of the settings on TubeMod does not work on my Arc Browser (does work on my Firefox though). 

Arc Chromium version 129.0.6668.71

**Comment by Myouboku** [comment]
Works fine for me, have you tried disabling other extensions ?
And do you experience this on Mac or Windows ?

**Comment by Pedro-Gregorio** [comment]
Hey, @Yezo ! Thank you for reporting it! Would you mind sharing more details so we can take a look?

**Comment by Pedro-Gregorio** [comment]
Hey, @Yezo !
Any update regarding this?
