### ISSUE TITLE
Add links to README

### ISSUE THREAD

**Issue by networkydev** [Pedro-Gregorio/TubeMod#4]
Great project (Got it recommended by Youtube)! It would be a good idea to add direct links to the addon pages in your README to prevent people from downloading the wrong extension.

- Firefox: https://addons.mozilla.org/en-US/firefox/addon/tubemod/
- Chromium (Google Chrome, Edge, Brave..): https://chromewebstore.google.com/detail/TubeMod/mhhalndcidpfcemnlidabgieccknndei

**Comment by Pedro-Gregorio** [comment]
Done! Added to 1.4.0 ReadMe
