### ISSUE TITLE
Sidebar settings incompatible with Youtube Premium

### ISSUE THREAD

**Issue by Kolpixx** [Pedro-Gregorio/TubeMod#6]
Because of the "YouTube Music" button that is displayed when using YouTube Premium, there is one more button in the sidebar which results in the sidebar settings from "Hide My Channel Button" to "Hide My Clips Button" not working as expected.

https://github.com/user-attachments/assets/b4ff9b70-70ea-42d5-829b-7078ef5dcdd5

**Comment by Pedro-Gregorio** [comment]
Hey @Kolpixx ! Thank you for the heads up, it's something I completely overlooked. Will handle this as soon as possible!

**Comment by Pedro-Gregorio** [comment]
@Kolpixx fixed, and will be available on the next version! :)
Can you reach out on X or Instagram to ensure this is also working on your end?

**Comment by Kolpixx** [comment]
> Can you reach out on X or Instagram to ensure this is also working on your end?

Of course! I can't message you on Twitter though, so you probably have to DM me first. My handle is @KolpixT

**Comment by Pedro-Gregorio** [comment]
Fixed! Will be available on 1.4.0, alonside the option to toggle "YouTube Music" and Transfers!
