### ISSUE TITLE
"Hide YouTube Footer" option breaks the creation of community posts

### ISSUE THREAD

**Issue by Kolpixx** [Pedro-Gregorio/TubeMod#60]
With "Hide YouTube Footer" toggled off:
![grafik](https://github.com/user-attachments/assets/5066511c-3159-4dbb-9090-9244dc05466d)

With "Hide YouTube Footer" toggled on:
![grafik](https://github.com/user-attachments/assets/fd7a8930-767e-48a1-aa94-bf9797296475)

**Comment by Pedro-Gregorio** [comment]
Hey, @Kolpixx ! Thank you for the heads up! I'll fix this today :)
