### ISSUE TITLE
feature request: Show thumbnail next to video player

### ISSUE THREAD

**Issue by ItzELECTR0** [Pedro-Gregorio/TubeMod#63]
Shows the thumbnail of the currently playing video at the top of the "Up Next" feed next to the video player. Clicking on the thumbnail in the feed would open a new tab with the thumbnail image itself, in case the user wants to download the thumbnail.
Could also include switch/button in case the video uses the A/B testing feature, to be able to switch between and view the thumbnails of the video.

(Inspired by the vidIQ extension which does something similar but is very bloated)

**Comment by Pedro-Gregorio** [comment]
Hey, @ItzELECTR0 ! Can you provide an example of this, please? 😄

**Comment by ItzELECTR0** [comment]
Sure thing @Pedro-Gregorio 
As I said before, this is inspired by [vidIQ](https://addons.mozilla.org/en-US/firefox/addon/vidiq-vision-youtube/) but that is a multipurpose extension with way too much bloat to install just for this one feature. Therefore alone it would be a great addition to TubeMod.

Keep in mind that in the following examples I am also using the [GX Mods](https://addons.mozilla.org/en-US/firefox/addon/gx-mods/) extension for Firefox with [YouTube GX](https://store.gx.me/mods/gcy6rz/youtube-gx/) & [YouTube Recolor](https://store.gx.me/mods/33gsd4/youtube-recolor/) active.

This is how it looks with vidIQ:
![image](https://github.com/user-attachments/assets/85c5c14d-3a38-4686-8118-6bd41ea5819c)

And this is how it could look with TubeMod:
(Concept made with Photoshop)
![Example2](https://github.com/user-attachments/assets/bd7f55ba-c1a8-43e1-a400-fe9ce226cdbc)

I hope this helps!
It's a really nifty feature I love from vidIQ but it slows down the page too much for me to keep using it, so I hope it makes it's way into TubeMod as standalone some day.

**Comment by ItzELECTR0** [comment]
P.S: YouTube provides thumbnails in 720p, so even if it looks low-res in my example, it wouldn't do so in the final product. Perhaps there could be a setting however to render the thumbnail in a lower resolution to save internet/data.

**Comment by Pedro-Gregorio** [comment]
I may be able to do something :)
Messed around for a bit, and got to this:
![Screenshot 2024-11-12 at 22 35 01](https://github.com/user-attachments/assets/95dda0bf-2291-4b59-811a-b6e45bf8597a)

Let's see 😄

**Comment by Pedro-Gregorio** [comment]
Aaaaand done with TubeMod! :)
![Screenshot 2024-11-12 at 23 19 04](https://github.com/user-attachments/assets/44d2ad66-c768-4982-9d7d-8dcc477d61de)
![Screenshot 2024-11-12 at 23 19 19](https://github.com/user-attachments/assets/d4f2c285-9afa-46d8-9748-3d3a901303d2)

**Comment by Pedro-Gregorio** [comment]
I know I'm a bit biased, but I do love the way this looks!
![Screenshot 2024-11-12 at 23 38 31](https://github.com/user-attachments/assets/01397e76-2b44-4370-9216-f8b7150f993a)

Thank you for the idea, @ItzELECTR0 , coming on 1.10.0 😄
