### ISSUE TITLE
Visualizações reaparecem

### ISSUE THREAD

**Issue by lighttigerXIV** [Pedro-Gregorio/TubeMod#64]
Eu estava a testar a extensão e reparei que mesmo tendo a opção de desativar as visualizações elas aparecem novamente quando o yotube faz aquele refresh com a animação quando é um novo video. Esconder a div `view-count` deveria funcionar :man_shrugging:. Isto no firefox, não testei em outros browsers.

![image](https://github.com/user-attachments/assets/a7bf98d9-9353-496e-8245-5c2cb0846a71)
![image](https://github.com/user-attachments/assets/c063a2f3-2d11-4339-885b-185501aac279)

**Comment by Pedro-Gregorio** [comment]
Boas! :)
Aqui está a funcionar em condições. Se atualizaste para a Versão 1.5, experimenta primeiro dar reset às settings.
Se estiver a esconder alguma coisa, em vez das views, avisa-me, please!

**Comment by Pedro-Gregorio** [comment]
Olá, @lighttigerXIV !
Algum update quanto a isto?

**Comment by lighttigerXIV** [comment]
> Olá, @lighttigerXIV !
> Algum update quanto a isto?

Sorry estava ocupado com a Uni. Eu à noite tento outra vez e vejo se o bug continua 🫡

**Comment by lighttigerXIV** [comment]
Continua XD
![image](https://github.com/user-attachments/assets/1fa1a6ef-0254-4c27-96fb-f452118b80d8)

**Comment by Pedro-Gregorio** [comment]
Bolas. Versão 1.6, right?

**Comment by lighttigerXIV** [comment]
> Bolas. Versão 1.6, right?

Sim. Mas vou testar no brave para ver se acontece tambem

**Comment by lighttigerXIV** [comment]
Tambem acontece o mesmo. Nao e muito importante porque eu gosto de ver as views mas ja vi que vai ser daqueles bugs dificis de resolver. Em ultimo caso tiras a opção na extensão.

![image](https://github.com/user-attachments/assets/865accbc-fa55-421d-b16a-dc2658dac63a)

**Comment by Pedro-Gregorio** [comment]
A questão é que está a funcionar do meu lado :D
![image](https://github.com/user-attachments/assets/dbc74938-cd1e-4c78-88ec-8e1950808577)

O que dificulta um bocado o processo de debug, mas vou validar na mesma :)

**Comment by lighttigerXIV** [comment]
> A questão é que está a funcionar do meu lado :D ![image](https://private-user-images.githubusercontent.com/110294853/377979373-dbc74938-cd1e-4c78-88ec-8e1950808577.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNzc2NzYsIm5iZiI6MTcyOTI3NzM3NiwicGF0aCI6Ii8xMTAyOTQ4NTMvMzc3OTc5MzczLWRiYzc0OTM4LWNkMWUtNGM3OC04OGVjLThlMTk1MDgwODU3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxODQ5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjFiMWZiZGIxNDk5N2IzZjI4MDMxNjRlNzM5N2E1MzYwZDU4NGIyYzgyY2ZhMjlkZWMyNmU2MGUwNDQzMTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VTdpOeGdVo856UrF5iAmCCBv9z32D-aefxrkeb4eU6I)
> 
> O que dificulta um bocado o processo de debug, mas vou validar na mesma :)

Se calhar nao percebest o problema 😅.
Ele esconde normalmente.
![image](https://github.com/user-attachments/assets/8d59ec53-4223-4f45-a414-0c30f4edca48)

So que se for um video recente de um canal grande o youtube atualiza as visualizacões de X em X segundos. Só nessa situação é que o problema acontece.
![image](https://github.com/user-attachments/assets/5d196b5e-21da-4fc0-94da-ce8fa8ebcd73)

Experimenta ver o [video](https://www.youtube.com/watch?v=vp5i0jQggK4) neste momento e espera até 1 minuto e vais ver que reaparecem

**Comment by Pedro-Gregorio** [comment]
Ahhhhhhhhh, desculpa, isto às sextas fica complicado! 😄 
Já consegui reproduzir do meu lado, vou ver o que dá para fazer :)

**Comment by Pedro-Gregorio** [comment]
Resolvido na versão 1.8.0 😄
