### ISSUE TITLE
Separators doesn't hide when hiding stuff from sidebar

### ISSUE THREAD

**Issue by qkunkii** [Pedro-Gregorio/TubeMod#69]
![image](https://github.com/user-attachments/assets/727dd16c-a3d3-4c1f-8e41-2769bd4a071a)
I'm talking about this. It's not a big deal, but it pisses me off.

**Comment by Pedro-Gregorio** [comment]
Hello! Yes, noticed it myself as well while doing some testing. Working on it to fix on the next release. Will leave this issue open to let you know about it :)

**Comment by Pedro-Gregorio** [comment]
Fixed, will be released on 1.7.0! Closing the issue now 😄
