### ISSUE TITLE
Hide additional buttons under video player

### ISSUE THREAD

**Issue by is-hiteshbehera** [Pedro-Gregorio/TubeMod#70]
Option to hide following buttons:
- "Join" Button
- "More" Button (used for "Report")

**Comment by Pedro-Gregorio** [comment]
Hey, @is-hiteshbehera !
Quick question, regarding the "More". Are you referring to those "..." ?
The Join is already ready to be released with 1.8.0 😄

**Comment by Pedro-Gregorio** [comment]
Both options to be released on 1.8.0 😄
