### ISSUE TITLE
Gibberish Instead of Text After Extension Translation

### ISSUE THREAD

**Issue by Valeron-bit** [Pedro-Gregorio/TubeMod#71]
Hello, Pedro Gregorio!
I have encountered the following problem. I wanted to translate the extension into my language for easier use (Russian). I translated the contents of the file \public\popup.html. However, when I imported the modified extension following your instructions, I encountered the following issue:

![image](https://github.com/user-attachments/assets/44eac1bd-3830-4e15-aaba-9c88e49068ef)

**Comment by Pedro-Gregorio** [comment]
Hey, @Valeron-bit ! Thank you for reaching out!
Well, now this is an interesting issue. I have no clue how this happened, but I'll definitely take a look, as soon as I can.

**Comment by Perseus333** [comment]
@Valeron-bit Yes, that was the case, now it is fixed, I have already made the PR on #71.

**Comment by Valeron-bit** [comment]
@Perseus333 It worked. I'm very grateful to you!

![image](https://github.com/user-attachments/assets/f0000b65-4c89-4439-92df-b67503185547)

**Comment by Pedro-Gregorio** [comment]
Thank you, @Perseus333 for the snappy fix, and @Valeron-bit for reporting the issue!
Closing this now, will be adding the PR to the upcoming version :)
