### ISSUE TITLE
Incorrect display of the button in the state

### ISSUE THREAD

**Issue by Valeron-bit** [Pedro-Gregorio/TubeMod#73]
Hello, Pedro Gregorio!
While testing the interface with a translated version, I encountered a display issue where the status button (On/Off) is misaligned due to the length of the translation text. Specifically, the button's text overflows or is pushed out of its container.

![image](https://github.com/user-attachments/assets/9d77a503-8178-46f1-9ed3-56ab7041c965)

**Comment by Pedro-Gregorio** [comment]
Hey, @Valeron-bit ! Thank you for reporting this, I'll fix this :)

**Comment by Perseus333** [comment]
Hi! This should be fixed on this PR: #77.

**Comment by Pedro-Gregorio** [comment]
Fixed by @Perseus333 and will be available on the next version :)
Thank you both!

**Comment by Valeron-bit** [comment]
@Perseus333 That helped, thank you so much!

![image](https://github.com/user-attachments/assets/adbbc6e4-d45a-4060-8c79-92586c61ccbd)
