### ISSUE TITLE
Feature Request - Save config 

### ISSUE THREAD

**Issue by Frxhb** [Pedro-Gregorio/TubeMod#81]
Hello,

I would like to request a feature that allows users to save the settings of the addon. This would be particularly useful for those who may need to reinstall or transfer the addon between different devices without having to manually reconfigure everything from scratch.

Thank you for considering this enhancement!

**Comment by Pedro-Gregorio** [comment]
Hey there, @Frxhb !

Consider it done 😄

**Comment by Pedro-Gregorio** [comment]
Small update: Saving the settings is now possible.
Working on uploading them, otherwise it's kind of useless to release it this way 🤣

**Comment by Pedro-Gregorio** [comment]
Hey, @Frxhb !
Whenever you can (and anyone else 😄 ), take a look at this, and let me know what you think, please!
https://www.loom.com/share/649e2d4f3ab541b5be0f58d1ce4c8e91?sid=e085ba12-0f91-4d05-97e0-650b32d4fbc6

**Comment by Pedro-Gregorio** [comment]
Thank you!
I'll just change 'Save Settings' to Export instead 😄 
This will be available on the next version, which I hope to release tonight!

**Comment by Frxhb** [comment]
Sounds great. 🙌🚀

**Comment by Frxhb** [comment]
Thanks for the quick addition of the save and import settings option. 

I just upgraded the addon to the latest version but when I export, reset and import the settings nothing changes, not even after a refresh.

**Comment by Pedro-Gregorio** [comment]
Hey @Frxhb !
There's this bug with YouTube when, in most cases, you have to reopen the tab after updating or installing the newer versions. Have you tried that?

**Comment by Frxhb** [comment]
Hey,

unfortunately this does not work either, even after restarting firefox etc. 
The export of the settings seems to work, but the import does not change anything.
Is there anything I can send you to debug more?
[tubeModSettings(3).json](https://github.com/user-attachments/files/17490622/tubeModSettings.3.json)

**Comment by Pedro-Gregorio** [comment]
Alright, I have no clue what changed between today and yesterday, but the feature does not seem to work on Firefox today, even though I tested it yesterday and had no troubles 😆

**Comment by VictuarVi** [comment]
The import functions seems to not work, both on Firefox forks and Chromium based browser. The exported JSON is full of backslashes: to fix it I removed them all and corrected the last entry (`tubemod_version`). However the import still doesn't work, even after restarting the browser.

Also the import confirmation at the end does not appear on Firefox forks.
