### ISSUE TITLE
Request to add a feature to hide all the recommended videos

### ISSUE THREAD

**Issue by MohamedAfraz** [Pedro-Gregorio/TubeMod#84]
Request to add a feature to hide all of the recommended feed. somewhat like the unhook chrome extension
<img width="567" alt="SCR-20241023-qbnj" src="https://github.com/user-attachments/assets/35303323-ee66-4a78-a7a5-c08d890c0edf">

**Comment by Pedro-Gregorio** [comment]
Hey @MohamedAfraz ! Consider it done!

**Comment by Pedro-Gregorio** [comment]
Done, will be available on the next version!
