### ISSUE TITLE
Suggestion Wall (End of the Video) is displaced with TubeMod enabled

### ISSUE THREAD

**Issue by RandomPersonUMet** [Pedro-Gregorio/TubeMod#87]
As the title says, at the end of a video the suggestion wall is displaced to the bottom right corner of the video player for some reason, even though I don't use the _"Hide Suggestion Wall (End of the Video)"_ feature (or any other feature under the _"Video"_ section).

I've only started seeing this bug since yesterday, when YouTube changed the progress bar colour, so it could be a server side change that caused this bug.

**Comment by RandomPersonUMet** [comment]
Nevermind just realised that this has been resolved and I just haven't gotten the update yet.

**Comment by RandomPersonUMet** [comment]
Nevermind just realised that this has been resolved and I just haven't gotten the update yet.

**Comment by Pedro-Gregorio** [comment]
Yep, the fix is coming tonight, alongside a new version :)
