### ISSUE TITLE
Hide Views Count 

### ISSUE THREAD

**Issue by matiasmacarioo** [Pedro-Gregorio/TubeMod#89]
Hide Views Count on the video section isn't working.

**Comment by Pedro-Gregorio** [comment]
Hey there. It's the only one that isn't working immediatly. Try reloading the page or opening another video and see if the problem persists, please.

**Comment by matiasmacarioo** [comment]
No, still seeing them, Also. I restarterd the pc to update windows and the setings from the video settings section were deleted, only those, the other ones were saved.

**Comment by Pedro-Gregorio** [comment]
That is wierd. Browser and TubeMod version, please? 😄

**Comment by matiasmacarioo** [comment]
Version 130.0.6723.70 (Official Build) (64-bit)
Current Version 1.8.0

**Comment by Pedro-Gregorio** [comment]
Fixed! Everything will be alright on the next version! 😄

**Comment by matiasmacarioo** [comment]
Great to hear that! Thanks!
